# Generated by Django 5.2.1 on 2025-10-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancedate',
            name='present',
        ),
        migrations.AddField(
            model_name='attendancedate',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('H', 'Holiday')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
