# Generated by Django 5.2.7 on 2025-10-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_course_attendancerecord_delete_attendancedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='is_present',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.IntegerField(choices=[(1, 'Present'), (2, 'Absent'), (3, 'Holiday/Cancelled')], default=1),
        ),
    ]
